services:
  recipecostcontrol.api:
    image: ${DOCKER_REGISTRY-}recipecostcontrolapi
    volumes:
      - ./.local:/external
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=/external/database/recipecostcontrol.db
    build:
      context: .
      dockerfile: RecipeCostControl.API/Dockerfile