// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeCostControl.Data.Context;

#nullable disable

namespace RecipeCostControl.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("MeasurementUnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.MeasurementUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits");

                    b.HasData(
                        new
                        {
                            Id = "kg",
                            Description = "Quilo"
                        },
                        new
                        {
                            Id = "gr",
                            Description = "Grama"
                        },
                        new
                        {
                            Id = "lt",
                            Description = "Litro"
                        },
                        new
                        {
                            Id = "ml",
                            Description = "Mililitro"
                        },
                        new
                        {
                            Id = "un",
                            Description = "Unidade"
                        });
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.MeasurementUnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasurementUnitFromId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MeasurementUnitToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(10,5)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitFromId");

                    b.HasIndex("MeasurementUnitToId");

                    b.ToTable("MeasurementUnitConversions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasurementUnitFromId = "kg",
                            MeasurementUnitToId = "gr",
                            Multiplier = 0.001m
                        },
                        new
                        {
                            Id = 2,
                            MeasurementUnitFromId = "gr",
                            MeasurementUnitToId = "kg",
                            Multiplier = 1000m
                        },
                        new
                        {
                            Id = 3,
                            MeasurementUnitFromId = "lt",
                            MeasurementUnitToId = "ml",
                            Multiplier = 0.001m
                        },
                        new
                        {
                            Id = 4,
                            MeasurementUnitFromId = "ml",
                            MeasurementUnitToId = "lt",
                            Multiplier = 1000m
                        });
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("MeasurementUnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Packaging");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("MeasurementUnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PackagingId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("PackagingId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("MeasurementUnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YieldQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.RecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementUnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeItem");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Ingredient", b =>
                {
                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeCostControl.Data.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.MeasurementUnitConversion", b =>
                {
                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnitFrom")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnitTo")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeasurementUnitFrom");

                    b.Navigation("MeasurementUnitTo");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Packaging", b =>
                {
                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Product", b =>
                {
                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeCostControl.Data.Entities.Packaging", "Packaging")
                        .WithMany()
                        .HasForeignKey("PackagingId");

                    b.HasOne("RecipeCostControl.Data.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Packaging");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Recipe", b =>
                {
                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.RecipeItem", b =>
                {
                    b.HasOne("RecipeCostControl.Data.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeCostControl.Data.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeCostControl.Data.Entities.Recipe", "Recipe")
                        .WithMany("Items")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeCostControl.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
