on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Recipe Cost Control Application
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Testes
      run: dotnet test --configuration Release
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        # Comandos para deploy da sua aplicação
        # Exemplo: dotnet publish -c Release -o ./publish
        # E depois copiar os arquivos para o servidor de destino
